# -*- coding: utf-8 -*-
"""Kompresi Video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHFq9nrX07ksTkwCzfwpFiGCJDuU5kbg

Install Libraries
"""

!pip install opencv-python-headless

import cv2
import os

"""Melakukan lossy compression menggunakan OpenCV"""

# Fungsi untuk melakukan lossy compression menggunakan OpenCV

def compress_lossy(video_path, output_path, quality):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Error: Video tidak dapat dibuka.")
        return

    frame_width = int(cap.get(3))
    frame_height = int(cap.get(4))
    fps = int(cap.get(5))
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    out = cv2.VideoWriter(output_path, fourcc, fps, (frame_width, frame_height))

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        out.write(frame)

    cap.release()
    out.release()
    cv2.destroyAllWindows()

"""Lossless compression menggunakan ffmpeg"""

def compress_lossless(video_path, output_path):
    os.system(f"ffmpeg -i {video_path} -c:v libx264 -preset slow -crf 20 -c:a copy {output_path}")

"""Masukkan Video"""

input_video_path = "jalan.mp4"

"""Output lossy compression

"""

output_lossy_path = "output_lossy_compressed_video.mp4"

"""Output lossless compression

"""

output_lossless_path = "output_lossless_compressed_video.mp4"

""" Lakukan lossy compression dengan kualitas 50 (sesuaikan dengan kebutuhan)

"""

compress_lossy(input_video_path, output_lossy_path, quality=50)

"""Lakukan lossless compression"""

compress_lossless(input_video_path, output_lossless_path)

"""Download hasil compression"""

print("Lossy compression selesai. Video tersimpan sebagai:", output_lossy_path)
print("Lossless compression selesai. Video tersimpan sebagai:", output_lossless_path)