# -*- coding: utf-8 -*-
"""Kompresi Audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9rQEPFnh_V1xn8-RGI9ShjPOxWowMEl

Install Libraries
"""

!pip install pydub soundfile
!apt-get install ffmpeg

"""Upload File"""

from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

"""Implementasi kompresi lossy"""

from pydub import AudioSegment

input_file = list(uploaded.keys())[0]
output_file_lossy = 'compressed_audio.mp3'

audio = AudioSegment.from_file(input_file)

audio.export(output_file_lossy, format='mp3', bitrate='128k')

print(f"File audio berhasil dikompresi ke {output_file_lossy}")

"""Implementasi kompresi lossless"""

temp_wav_file = 'temp_audio.wav'
audio.export(temp_wav_file, format='wav')

import soundfile as sf

output_file_lossless = 'compressed_audio.flac'

data, samplerate = sf.read(temp_wav_file)

sf.write(output_file_lossless, data, samplerate, format='FLAC')

print(f"File audio berhasil dikompresi ke {output_file_lossless}")

"""Download Hasil Kompresi"""

from google.colab import files

files.download(output_file_lossy)

files.download(output_file_lossless)